# Generated by Django 4.0 on 2021-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eaddress',
            field=models.CharField(max_length=20),
        ),
    ]
