# Generated by Django 4.0 on 2021-12-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_eaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eaddress',
            field=models.CharField(max_length=20),
        ),
    ]
